# since this is image is built with root context, most of the files
# need to be excluded for faster builds and to avoid spoiling build
# cache due to unchecked files (like configs or random binaries)
*

# must-have toplevel files
!/Makefile*
!/go.sum
!/go.mod
!/VERSION
!/GIT_VERSION
# TODO: this is currently a make dependency, but should be removed
# in the future
!/Dockerfile

# directories
!/api
!/pkg
!/vendor
!/operator
